-- ============================================================
-- EduPath Database
-- File: 007_gamification.sql
-- Description:
-- Milestone 7 — Gamification
-- XP events, achievements, daily missions, streaks.
-- See doc/11_GAMIFICATION.md and doc/26_PRODUCT_LEXICON.md
--
-- Depends on: 001_enums.sql, 002_profiles.sql
-- ============================================================

----------------------------------------------------------
-- XP EVENTS
-- Ledger of every XP-earning event per user.
-- profiles.xp holds the running total.
----------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.xp_events (

    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    user_id UUID NOT NULL
        REFERENCES public.profiles(id)
        ON DELETE CASCADE,

    event_type xp_event_type NOT NULL,

    xp_earned INTEGER NOT NULL DEFAULT 0
        CHECK (xp_earned >= 0),

    reference_id UUID,

    description TEXT,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()

);

----------------------------------------------------------
-- ACHIEVEMENTS
-- Master catalogue. Public read.
----------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.achievements (

    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    name TEXT NOT NULL UNIQUE,

    description TEXT NOT NULL,

    icon TEXT NOT NULL DEFAULT 'trophy',

    category achievement_category NOT NULL DEFAULT 'learning',

    xp_reward INTEGER NOT NULL DEFAULT 0
        CHECK (xp_reward >= 0),

    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()

);

----------------------------------------------------------
-- USER ACHIEVEMENTS
-- Records when a student earns an achievement.
----------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.user_achievements (

    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    user_id UUID NOT NULL
        REFERENCES public.profiles(id)
        ON DELETE CASCADE,

    achievement_id UUID NOT NULL
        REFERENCES public.achievements(id)
        ON DELETE CASCADE,

    earned_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    UNIQUE(user_id, achievement_id)

);

----------------------------------------------------------
-- DAILY MISSIONS
-- Mission templates. Generated by CLE each morning.
----------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.daily_missions (

    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    title TEXT NOT NULL,

    description TEXT NOT NULL,

    xp_reward INTEGER NOT NULL DEFAULT 10
        CHECK (xp_reward >= 0),

    category TEXT NOT NULL DEFAULT 'learning',

    is_active BOOLEAN NOT NULL DEFAULT TRUE,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()

);

----------------------------------------------------------
-- USER DAILY MISSIONS
-- A student's assigned mission for a specific day.
----------------------------------------------------------

CREATE TABLE IF NOT EXISTS public.user_daily_missions (

    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    user_id UUID NOT NULL
        REFERENCES public.profiles(id)
        ON DELETE CASCADE,

    mission_id UUID NOT NULL
        REFERENCES public.daily_missions(id)
        ON DELETE CASCADE,

    assigned_date DATE NOT NULL DEFAULT CURRENT_DATE,

    is_completed BOOLEAN NOT NULL DEFAULT FALSE,

    completed_at TIMESTAMPTZ,

    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    UNIQUE(user_id, mission_id, assigned_date)

);

----------------------------------------------------------
-- UPDATED_AT TRIGGERS
----------------------------------------------------------

CREATE TRIGGER achievements_updated_at
BEFORE UPDATE ON public.achievements
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER daily_missions_updated_at
BEFORE UPDATE ON public.daily_missions
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER user_daily_missions_updated_at
BEFORE UPDATE ON public.user_daily_missions
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

----------------------------------------------------------
-- INDEXES
----------------------------------------------------------

CREATE INDEX IF NOT EXISTS idx_xp_events_user_id
ON public.xp_events(user_id);

CREATE INDEX IF NOT EXISTS idx_xp_events_type
ON public.xp_events(user_id, event_type);

CREATE INDEX IF NOT EXISTS idx_xp_events_recent
ON public.xp_events(user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_achievements_category
ON public.achievements(category);

CREATE INDEX IF NOT EXISTS idx_user_achievements_user_id
ON public.user_achievements(user_id);

CREATE INDEX IF NOT EXISTS idx_user_daily_missions_user_id
ON public.user_daily_missions(user_id);

CREATE INDEX IF NOT EXISTS idx_user_daily_missions_date
ON public.user_daily_missions(user_id, assigned_date DESC);

CREATE INDEX IF NOT EXISTS idx_user_daily_missions_incomplete
ON public.user_daily_missions(user_id, assigned_date)
WHERE is_completed = FALSE;

----------------------------------------------------------
-- ENABLE RLS
----------------------------------------------------------

ALTER TABLE public.xp_events             ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.achievements          ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_achievements     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.daily_missions        ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_daily_missions   ENABLE ROW LEVEL SECURITY;

----------------------------------------------------------
-- RLS POLICIES
----------------------------------------------------------

CREATE POLICY "Users can read own XP events"
ON public.xp_events
FOR SELECT
TO authenticated
USING (auth.uid() = user_id);

CREATE POLICY "Authenticated users can read achievements"
ON public.achievements
FOR SELECT
TO authenticated
USING (true);

CREATE POLICY "Users can read own achievements"
ON public.user_achievements
FOR ALL
TO authenticated
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Authenticated users can read missions"
ON public.daily_missions
FOR SELECT
TO authenticated
USING (true);

CREATE POLICY "Users can manage own daily missions"
ON public.user_daily_missions
FOR ALL
TO authenticated
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

----------------------------------------------------------
-- SEED — Achievements
-- From doc/11_GAMIFICATION.md
----------------------------------------------------------

INSERT INTO public.achievements
    (name, description, icon, category, xp_reward)
VALUES
    ('First Step',           'Completed your first study session.',                      'footprints', 'learning', 50),
    ('Memory Guardian',      'Recovered 100 forgotten concepts.',                        'shield',     'revision', 500),
    ('Consistency Champion', 'Maintained a 30-day study streak.',                        'flame',      'streak',   1000),
    ('Concept Master',       'Achieved full confidence in a complete chapter.',          'star',       'learning', 750),
    ('PYQ Slayer',           'Solved 100 previous-year questions.',                      'sword',      'quiz',     600),
    ('Memory Rescuer',       'Recovered 10 concepts with critically low confidence.',    'heart',      'revision', 300),
    ('Quiz Ace',             'Scored 100% on a quiz.',                                   'target',     'quiz',     200),
    ('Knowledge Seeker',     'Studied 10 different concepts.',                           'book',       'learning', 150)
ON CONFLICT (name) DO NOTHING;

----------------------------------------------------------
-- SEED — Daily Mission Templates
----------------------------------------------------------

INSERT INTO public.daily_missions
    (title, description, xp_reward, category)
VALUES
    ('Weak Topic Warrior',   'Review one weak topic from your Knowledge Constellation.', 10, 'revision'),
    ('Concept Recovery',     'Recover one forgotten concept with low confidence.',        15, 'revision'),
    ('Smart Recall',         'Solve five adaptive questions from your weak areas.',       20, 'quiz'),
    ('Streak Keeper',        'Complete any study session to maintain your streak.',       10, 'streak'),
    ('Knowledge Builder',    'Study one new concept you have not explored yet.',          15, 'learning'),
    ('Brain Warm-Up',        'Complete today''s Daily Brain Warm-Up session.',            25, 'revision')
ON CONFLICT DO NOTHING;

----------------------------------------------------------
-- VERIFY
----------------------------------------------------------

SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'public'
ORDER BY table_name;